In [7]:
import numpy as np


# Creating Numpy Arrays from Python List

In [4]:
a = np.array([4.14,4.2,2,3])
print(a)

[4.14 4.2  2.   3.  ]


In [5]:
type(a)

numpy.ndarray

In [8]:
#convert -> float
np.array([1.2,3,4],dtype='float32')

array([1.2, 3. , 4. ], dtype=float32)

In [12]:
a2 = np.array([[1,2,3],[3,4,5]])
print(a2)


[[1 2 3]
 [3 4 5]]


In [13]:
a2.shape

(2, 3)

In [14]:
a2.ndim

2

In [15]:
a2.size

6

# Creating Numpy Array from Scratch
#zeros , ones ,full ,arange , linspace

In [24]:
np.zeros([2,4],dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [26]:
np.ones([2,3],dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [27]:
np.arange(0,10,2,dtype=int)

array([0, 2, 4, 6, 8])

In [28]:
np.full([3,5],6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [32]:
np.linspace(0.1,5)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3,
       1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6,
       2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9,
       4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. ])

# `Random `

In [34]:
np.random.random((4,4))

array([[0.34903425, 0.99667622, 0.88179174, 0.02505604],
       [0.39959646, 0.42821604, 0.81772741, 0.94059687],
       [0.92210654, 0.7829088 , 0.00122587, 0.25186532],
       [0.6690669 , 0.28015261, 0.33088646, 0.5797359 ]])

In [37]:
#seed
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [42]:
np.random.normal(0,1,(3,3))
#normal('mean','do lech chuan','size')

array([[-0.89546656,  0.3869025 , -0.51080514],
       [-1.18063218, -0.02818223,  0.42833187],
       [ 0.06651722,  0.3024719 , -0.63432209]])

In [49]:
np.random.randint(0,10,[3,5])

array([[8, 2, 3, 9, 7],
       [5, 3, 4, 5, 3],
       [3, 7, 9, 9, 9]])

In [50]:
#tuong tu nhu random la rand()
np.random.rand(3,4)

array([[0.37329075, 0.42007537, 0.05058812, 0.36549611],
       [0.01662797, 0.23074234, 0.7649117 , 0.94412352],
       [0.74999925, 0.33940382, 0.48954894, 0.33898512]])

# Array indexing and Slicing

In [53]:
x1= np.random.randint(20,size=6)
print(x1)

[ 8  1 17 16  3  8]


In [56]:
x1[4],x1[0],x1[-1]

(3, 8, 8)

In [59]:
x2 = np.random.randint(10,size = (3,4))
print(x2)

[[4 2 5 5]
 [5 2 5 7]
 [7 6 1 6]]


In [62]:
x2[2,3]
#[row,column]

6

In [63]:
#change
x2[2,3] = 10

# Slicing([start:stop:step])

In [66]:
 x1

array([ 8,  1, 17, 16,  3,  8])

In [67]:
x1[0:3]

array([ 8,  1, 17])

In [69]:
x1[2:]

array([17, 16,  3,  8])

In [71]:
x1[::2]
#step - ::

array([ 8, 17,  3])

In [72]:
x2

array([[ 4,  2,  5,  5],
       [ 5,  2,  5,  7],
       [ 7,  6,  1, 10]])

In [73]:
x2[:2,:3]

array([[4, 2, 5],
       [5, 2, 5]])

# Reshaping of Array  & Tranpose

In [77]:
grid = np.arange(1,10)
grid.shape

(9,)

In [78]:
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
x = np.array([1,2,3])
print(x)

[1 2 3]


In [82]:
x.reshape(1,3).shape

(1, 3)

In [85]:
x = np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [87]:
x.T
#row <-> column

array([[1, 3],
       [2, 4]])

In [88]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [89]:
np.concatenate((x,y))

array([1, 2, 3, 4, 5, 6])

In [10]:
#vstack -> noi theo chieu doc
#hstack -> noi theo chieu ngang 
x = np.array([1,2,3])
grid = np.array([[3,4,5],[6,7,8]])
np.vstack((x,grid))

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

# Splitting of Array

In [11]:
x=np.array([1,2,3,4,5,6,7,8,9,10])

In [14]:
x1,x2,x3 = np.split(x,[3,6])
#tach array

In [17]:
x3

array([ 7,  8,  9, 10])

# Broadcasting and Vectorized operations

In [19]:
a=np.arange(3)
a

array([0, 1, 2])

In [21]:
a+5 #Broadcasting

array([5, 6, 7])

# Manipulating & Comparing Array

In [22]:
list_number = [1,2,3]

In [23]:
ll = np.array(list_number)

In [24]:
sum(ll)

6

In [29]:
#Create a massive Numpy array
massive_array = np.random.random(10000)
massive_array[:5]
massive_array.size

10000

In [30]:
massive_array = np.random.random(10000)
massive_array[:5]
massive_array.shape

(10000,)

In [32]:
%timeit sum(massive_array) #nhieu time 

%timeit np.sum(massive_array) #it time 

860 µs ± 70.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
7.91 µs ± 340 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [33]:
np.mean(massive_array)

0.502808315252259

In [34]:
np.max(massive_array)

0.9998299569081373

# Statistics - xac suat thong ke
#Standard Deviation(độ lệch chuẩn) and Variance(phương sai)

In [35]:
dog_height=[600,470,170,430,300]
dog_height = np.array(dog_height)

In [36]:
#do lech chuan
np.std(dog_height)

147.32277488562318

In [37]:
#phuong sai
np.var(dog_height)

21704.0

In [38]:
#do lech chuan can bac 2
np.sqrt(np.var(dog_height))

147.32277488562318

# Sorting Arrays - quicksort algorithm

In [39]:
x = np.array([3,1,2,4,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [41]:
np.argsort(x)
# return index cua cac element khi sort

array([1, 2, 0, 3, 4], dtype=int64)

In [44]:
np.random.seed(42)#random ra cac lan khong doi dung seed
MatA = np.random.randint(0,10,size=(4,6))

In [45]:
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [46]:
np.sort(MatA,axis=0) #sort column

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [47]:
np.sort(MatA,axis=1) #sort row

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

# Linear Algebra - Dai do tuyen tinh

In [48]:
A = np.array([[1,2,3],
             [4,5,6],
              [7,8,9]])

In [49]:
B = np.array([[6,5],
             [3,4],
             [2,1]])

In [54]:
# dot product A and B  - tich vo huong (row * column)
# A(3x3) \ B(3x2)
A.dot(B)

array([[18, 16],
       [51, 46],
       [84, 76]])

In [53]:
A@B #giong voi A.dot(B)

array([[18, 16],
       [51, 46],
       [84, 76]])

In [56]:
 # B dot A 
# B(3x2) A(3x3)
B.T @ A

array([[32, 43, 54],
       [28, 38, 48]])

# Example


In [57]:
np.random.seed(0)
sales_amouts = np.random.randint(20,size=(5,3))

In [58]:
sales_amouts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [69]:
#creat dataFrame
import pandas as pd
weekly_sales = pd.DataFrame(sales_amouts,index = ['Mon','Tues','Wed','Thurs','Fril'],
                            columns=['Almond Butter','Peanut Butter','Cashew Butter'])
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fril               1              6              7

In [67]:
#create a price array
prices = np.array([10,8,12])

In [74]:
butter_prices = pd.DataFrame(prices.reshape(1,3),index=['Price'],
                             columns=['Almond Butter','Peanut Butter','Cashew Butter'])

In [75]:
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [77]:
weekly_sales.shape,butter_prices.T.shape

((5, 3), (3, 1))

In [78]:
total_prices = weekly_sales.dot(butter_prices.T)

In [79]:
total_prices

Price
Mon      240
Tues     138
Wed      458
Thurs    232
Fril     142

In [80]:
weekly_sales['Total Price'] = total_prices

In [81]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total Price
Mon               12             15              0          240
Tues               3              3              7          138
Wed                9             19             18          458
Thurs              4              6             12          232
Fril               1              6              7          142